var units = {
"INAU":{"name":"2013 Presidential Inauguration","type":"","state":"District of Columbia"},
"ABLI":{"name":"Abraham Lincoln Birthplace","type":"National Historical Park","state":"Kentucky"},
"ACAD":{"name":"Acadia","type":"National Park","state":"Maine"},
"ADAM":{"name":"Adams","type":"National Historical Park","state":"Massachusetts"},
"AFAM":{"name":"African American Civil War Memorial","type":"National Memorial","state":"District of Columbia"},
"AFBG":{"name":"African Burial Ground","type":"National Monument","state":"New York"},
"AGFO":{"name":"Agate Fossil Beds","type":"National Monument","state":"Nebraska"},
"ALKA":{"name":"Ala Kahakai","type":"National Historic Trail","state":"Hawai'i"},
"ALAG":{"name":"Alagnak","type":"Wild River","state":"Alaska"},
"ANCH":{"name":"Alaska Public Lands","type":"","state":"Alaska"},
"ALCA":{"name":"Alcatraz Island","type":"","state":"California"},
"ALEU":{"name":"Aleutian World War II","type":"National Historic Area","state":"Alaska"},
"ALFL":{"name":"Alibates Flint Quarries","type":"National Monument","state":"Texas"},
"ALPO":{"name":"Allegheny Portage Railroad","type":"National Historic Site","state":"Pennsylvania"},
"AMME":{"name":"American Memorial","type":"Park","state":"Northern Mariana Islands"},
"AMIS":{"name":"Amistad","type":"National Recreation Area","state":"Texas"},
"ANAC":{"name":"Anacostia","type":"Park","state":"District of Columbia"},
"ANDE":{"name":"Andersonville","type":"National Historic Site","state":"Georgia"},
"ANJO":{"name":"Andrew Johnson","type":"National Historic Site","state":"Tennessee"},
"ANIA":{"name":"Aniakchak","type":"National Monument & Preserve","state":"Alaska"},
"ANTI":{"name":"Antietam","type":"National Battlefield","state":"Maryland"},
"APIS":{"name":"Apostle Islands","type":"National Lakeshore","state":"Wisconsin"},
"APPA":{"name":"Appalachian","type":"National Scenic Trail","state":"CT,GA,MA,MD,ME,NC,NH,NJ,NY,PA,TN,VA,VT,WV"},
"APCO":{"name":"Appomattox Court House","type":"National Historical Park","state":"Virginia"},
"ARMO":{"name":"Arabia Mountain","type":"National Heritage Area","state":"Georgia"},
"ARCH":{"name":"Arches","type":"National Park","state":"Utah"},
"ARPO":{"name":"Arkansas Post","type":"National Memorial","state":"Arkansas"},
"ARHO":{"name":"Arlington House, The Robert  E. Lee Memorial","type":"","state":"Virginia"},
"ASIS":{"name":"Assateague Island","type":"National Seashore","state":"MD,VA"},
"ATTR":{"name":"Atchafalaya","type":"National Heritage Area","state":"Louisiana"},
"AUCA":{"name":"Augusta Canal","type":"National Heritage Area","state":"Georgia"},
"AZRU":{"name":"Aztec Ruins","type":"National Monument","state":"New Mexico"},
"BADL":{"name":"Badlands","type":"National Park","state":"South Dakota"},
"BALT":{"name":"Baltimore","type":"National Heritage Area","state":"Maryland"},
"BAWA":{"name":"Baltimore-Washington","type":"Parkway","state":"Maryland"},
"BAND":{"name":"Bandelier","type":"National Monument","state":"New Mexico"},
"BEOL":{"name":"Bent's Old Fort","type":"National Historic Site","state":"Colorado"},
"BELA":{"name":"Bering Land Bridge","type":"National Preserve","state":"Alaska"},
"BIBE":{"name":"Big Bend","type":"National Park","state":"Texas"},
"BICY":{"name":"Big Cypress","type":"National Preserve","state":"Florida"},
"BIHO":{"name":"Big Hole","type":"National Battlefield","state":"Montana"},
"BISO":{"name":"Big South Fork","type":"National River & Recreation Area","state":"KY,TN"},
"BITH":{"name":"Big Thicket","type":"National Preserve","state":"Texas"},
"BICA":{"name":"Bighorn Canyon","type":"National Recreation Area","state":"MT,WY"},
"BISC":{"name":"Biscayne","type":"National Park","state":"Florida"},
"BLCA":{"name":"Black Canyon Of The Gunnison","type":"National Park","state":"Colorado"},
"BLAC":{"name":"Blackstone River Valley","type":"National Heritage Corridor","state":"MA,RI"},
"BLRN":{"name":"Blue Ridge","type":"National Heritage Area","state":"North Carolina"},
"BLRI":{"name":"Blue Ridge","type":"Parkway","state":"NC,VA"},
"BLUE":{"name":"Bluestone","type":"National Scenic River","state":"West Virginia"},
"BOWA":{"name":"Booker T Washington","type":"National Monument","state":"Virginia"},
"BOAF":{"name":"Boston African American","type":"National Historic Site","state":"Massachusetts"},
"BOHA":{"name":"Boston Harbor Islands","type":"National Recreation Area","state":"Massachusetts"},
"BOST":{"name":"Boston","type":"National Historical Park","state":"Massachusetts"},
"BRCR":{"name":"Brices Cross Roads","type":"National Battlefield Site","state":"Mississippi"},
"BRVB":{"name":"Brown v. Board of Education","type":"National Historic Site","state":"Kansas"},
"BRCA":{"name":"Bryce Canyon","type":"National Park","state":"Utah"},
"BUIS":{"name":"Buck Island Reef","type":"National Monument","state":"Virgin Islands"},
"BUFF":{"name":"Buffalo","type":"National River","state":"Arkansas"},
"CABR":{"name":"Cabrillo","type":"National Monument","state":"California"},
"CALA":{"name":"Cache La Poudre","type":"River Corridor","state":"Colorado"},
"CALI":{"name":"California","type":"National Historic Trail","state":"CA,CO,ID,KS,MO,NE,NV,OR,UT,WY"},
"CANA":{"name":"Canaveral","type":"National Seashore","state":"Florida"},
"CARI":{"name":"Cane River Creole","type":"National Historical Park","state":"Louisiana"},
"CRHA":{"name":"Cane River","type":"National Heritage Area","state":"Louisiana"},
"CACH":{"name":"Canyon De Chelly","type":"National Monument","state":"Arizona"},
"CANY":{"name":"Canyonlands","type":"National Park","state":"Utah"},
"CACO":{"name":"Cape Cod","type":"National Seashore","state":"Massachusetts"},
"CAHA":{"name":"Cape Hatteras","type":"National Seashore","state":"North Carolina"},
"CAME":{"name":"Cape Henry Memorial","type":"Part of Colonial National Historical Park","state":"Virginia"},
"CAKR":{"name":"Cape Krusenstern","type":"National Monument","state":"Alaska"},
"CALO":{"name":"Cape Lookout","type":"National Seashore","state":"North Carolina"},
"CAHI":{"name":"Capitol Hill Parks","type":"","state":"District of Columbia"},
"CARE":{"name":"Capitol Reef","type":"National Park","state":"Utah"},
"CAJO":{"name":"Captain John Smith Chesapeake","type":"National Historic Trail","state":"VA,MD,DE,DC,PA,NY"},
"CAVO":{"name":"Capulin Volcano","type":"National Monument","state":"New Mexico"},
"CARL":{"name":"Carl Sandburg Home","type":"National Historic Site","state":"North Carolina"},
"CAVE":{"name":"Carlsbad Caverns","type":"National Park","state":"New Mexico"},
"CAWO":{"name":"Carter G. Woodson Home","type":"National Historic Site","state":"District of Columbia"},
"CAGR":{"name":"Casa Grande Ruins","type":"National Monument","state":"Arizona"},
"CASA":{"name":"Castillo De San Marcos","type":"National Monument","state":"Florida"},
"CACL":{"name":"Castle Clinton","type":"National Monument","state":"New York"},
"CATO":{"name":"Catoctin Mountain","type":"Park","state":"Maryland"},
"CEBR":{"name":"Cedar Breaks","type":"National Monument","state":"Utah"},
"CEBE":{"name":"Cedar Creek & Belle Grove","type":"National Historical Park","state":"Virginia"},
"CHCU":{"name":"Chaco Culture","type":"National Historical Park","state":"New Mexico"},
"CHAM":{"name":"Chamizal","type":"National Memorial","state":"Texas"},
"CHVA":{"name":"Champlain Valley","type":"National Heritage Partnership","state":"NY, VT"},
"CHIS":{"name":"Channel Islands","type":"National Park","state":"California"},
"CHPI":{"name":"Charles Pinckney","type":"National Historic Site","state":"South Carolina"},
"CHYO":{"name":"Charles Young Buffalo Soldiers","type":"National Monument","state":"Ohio"},
"CHAT":{"name":"Chattahoochee River","type":"National Recreation Area","state":"Georgia"},
"CHBL":{"name":"Cherry Blossom Festival","type":"","state":"District of Columbia"},
"CHOH":{"name":"Chesapeake & Ohio Canal","type":"National Historical Park","state":"DC,MD,WV"},
"CBGN":{"name":"Chesapeake Bay Gateways and Watertrails Network","type":"","state":"DC,MD,NY,PA,VA,WV,DE"},
"CBPO":{"name":"Chesapeake Bay","type":"","state":"DC,MD,NY,PA,VA,WV"},
"CHCH":{"name":"Chickamauga & Chattanooga","type":"National Military Park","state":"GA,TN"},
"CHIC":{"name":"Chickasaw","type":"National Recreation Area","state":"Oklahoma"},
"CHIR":{"name":"Chiricahua","type":"National Monument","state":"Arizona"},
"CHRI":{"name":"Christiansted","type":"National Historic Site","state":"Virgin Islands"},
"CIRO":{"name":"City Of Rocks","type":"National Reserve","state":"Idaho"},
"CWDW":{"name":"Civil War Defenses of Washington","type":"","state":"District of Columbia"},
"CLBA":{"name":"Clara Barton","type":"National Historic Site","state":"Maryland"},
"CLMO":{"name":"Claude Moore Colonial Farm","type":"","state":"Virginia"},
"COAL":{"name":"Coal","type":"National Heritage Area","state":"West Virginia"},
"COLO":{"name":"Colonial","type":"National Historical Park","state":"Virginia"},
"COLM":{"name":"Colorado","type":"National Monument","state":"Colorado"},
"CONG":{"name":"Congaree","type":"National Park","state":"South Carolina"},
"COGA":{"name":"Constitution Gardens","type":"","state":"District of Columbia"},
"CORO":{"name":"Coronado","type":"National Memorial","state":"Arizona"},
"COWP":{"name":"Cowpens","type":"National Battlefield","state":"South Carolina"},
"CRLA":{"name":"Crater Lake","type":"National Park","state":"Oregon"},
"CRMO":{"name":"Craters Of The Moon","type":"National Monument & Preserve","state":"Idaho"},
"XRDS":{"name":"Crossroads of the American Revolution","type":"National Heritage Area","state":"New Jersey"},
"CUGA":{"name":"Cumberland Gap","type":"National Historical Park","state":"KY,TN,VA"},
"CUIS":{"name":"Cumberland Island","type":"National Seashore","state":"Georgia"},
"CURE":{"name":"Curecanti","type":"National Recreation Area","state":"Colorado"},
"CUVA":{"name":"Cuyahoga Valley","type":"National Park","state":"Ohio"},
"CECH":{"name":"César E. Chávez","type":"National Monument","state":"California"},
"DABE":{"name":"David Berger","type":"National Memorial","state":"Ohio"},
"DAAV":{"name":"Dayton Aviation Heritage","type":"National Historical Park","state":"Ohio"},
"DESO":{"name":"De Soto","type":"National Memorial","state":"Florida"},
"DEVA":{"name":"Death Valley","type":"National Park","state":"CA,NV"},
"DELE":{"name":"Delaware & Lehigh","type":"National Heritage Corridor","state":"Pennsylvania"},
"DEWA":{"name":"Delaware Water Gap","type":"National Recreation Area","state":"NJ,PA"},
"DENA":{"name":"Denali","type":"National Park & Preserve","state":"Alaska"},
"DEPO":{"name":"Devils Postpile","type":"National Monument","state":"California"},
"DETO":{"name":"Devils Tower","type":"National Monument","state":"Wyoming"},
"DINO":{"name":"Dinosaur","type":"National Monument","state":"CO,UT"},
"DRTO":{"name":"Dry Tortugas","type":"National Park","state":"Florida"},
"DSCW":{"name":"DSC Workflows","type":"","state":""},
"EBLA":{"name":"Ebey's Landing","type":"National Historical Reserve","state":"Washington"},
"EDAL":{"name":"Edgar Allan Poe","type":"National Historic Site","state":"Pennsylvania"},
"EFMO":{"name":"Effigy Mounds","type":"National Monument","state":"Iowa"},
"EISE":{"name":"Eisenhower","type":"National Historic Site","state":"Pennsylvania"},
"ELTE":{"name":"El Camino Real de los Tejas","type":"National Historic Trail","state":"TX,LA"},
"ELCA":{"name":"El Camino Real de Tierra Adentro","type":"National Historic Trail","state":"NM,TX"},
"ELMA":{"name":"El Malpais","type":"National Monument","state":"New Mexico"},
"ELMO":{"name":"El Morro","type":"National Monument","state":"New Mexico"},
"ELRO":{"name":"Eleanor Roosevelt","type":"National Historic Site","state":"New York"},
"ELIS":{"name":"Ellis Island","type":"Part of Statue of Liberty National Monument","state":"NJ,NY"},
"ERIE":{"name":"Erie Canalway","type":"National Heritage Corridor","state":"New York"},
"ESSE":{"name":"Essex","type":"National Heritage Area","state":"Massachusetts"},
"EUON":{"name":"Eugene O'Neill","type":"National Historic Site","state":"California"},
"EVER":{"name":"Everglades","type":"National Park","state":"Florida"},
"FATI":{"name":"Fallen Timbers Battlefield and Fort Miamis","type":"National Historic Site","state":"Ohio"},
"FEHA":{"name":"Federal Hall","type":"National Memorial","state":"New York"},
"FIIS":{"name":"Fire Island","type":"National Seashore","state":"New York"},
"FILA":{"name":"First Ladies","type":"National Historic Site","state":"Ohio"},
"FRST":{"name":"First State","type":"National Historical Park","state":"DE,PA"},
"FLNI":{"name":"Flight 93","type":"National Memorial","state":"Pennsylvania"},
"FLFO":{"name":"Florissant Fossil Beds","type":"National Monument","state":"Colorado"},
"FOTH":{"name":"Ford's Theatre","type":"National Historic Site","state":"District of Columbia"},
"FOBO":{"name":"Fort Bowie","type":"National Historic Site","state":"Arizona"},
"FOCA":{"name":"Timucuan","type":"Ecological & Historic Preserve","state":"Florida"},
"FODA":{"name":"Fort Davis","type":"National Historic Site","state":"Texas"},
"FODO":{"name":"Fort Donelson","type":"National Battlefield","state":"Tennessee"},
"FODU":{"name":"Fort Dupont Park","type":"","state":"District of Columbia"},
"FOFO":{"name":"Fort Foote","type":"Park","state":"Maryland"},
"FOFR":{"name":"Fort Frederica","type":"National Monument","state":"Georgia"},
"FOLA":{"name":"Fort Laramie","type":"National Historic Site","state":"Wyoming"},
"FOLS":{"name":"Fort Larned","type":"National Historic Site","state":"Kansas"},
"FOMA":{"name":"Fort Matanzas","type":"National Monument","state":"Florida"},
"FOMC":{"name":"Fort McHenry","type":"National Monument and Historic Shrine","state":"Maryland"},
"FOMR":{"name":"Fort Monroe","type":"National Monument","state":"Virginia"},
"FONE":{"name":"Fort Necessity","type":"National Battlefield","state":"Pennsylvania"},
"FOPO":{"name":"Fort Point","type":"National Historic Site","state":"California"},
"FOPU":{"name":"Fort Pulaski","type":"National Monument","state":"Georgia"},
"FORA":{"name":"Fort Raleigh","type":"National Historic Site","state":"North Carolina"},
"FOSC":{"name":"Fort Scott","type":"National Historic Site","state":"Kansas"},
"FOSM":{"name":"Fort Smith","type":"National Historic Site","state":"AR,OK"},
"FOST":{"name":"Fort Stanwix","type":"National Monument","state":"New York"},
"FOSU":{"name":"Fort Sumter","type":"National Monument","state":"South Carolina"},
"FOUN":{"name":"Fort Union","type":"National Monument","state":"New Mexico"},
"FOUS":{"name":"Fort Union Trading Post","type":"National Historic Site","state":"MT,ND"},
"FOVA":{"name":"Fort Vancouver","type":"National Historic Site","state":"OR,WA"},
"FOWA":{"name":"Fort Washington","type":"Park","state":"Maryland"},
"FOBU":{"name":"Fossil Butte","type":"National Monument","state":"Wyoming"},
"FRDE":{"name":"Franklin Delano Roosevelt","type":"Memorial","state":"District of Columbia"},
"FRDO":{"name":"Frederick Douglass","type":"National Historic Site","state":"District of Columbia"},
"FRLA":{"name":"Frederick Law Olmsted","type":"National Historic Site","state":"Massachusetts"},
"FRSP":{"name":"Fredericksburg & Spotsylvania","type":"National Military Park","state":"Virginia"},
"FRWA":{"name":"Freedom's Way","type":"National Heritage Area","state":"NH, MA"},
"FRHI":{"name":"Friendship Hill","type":"National Historic Site","state":"Pennsylvania"},
"GAAR":{"name":"Gates Of The Arctic","type":"National Park & Preserve","state":"Alaska"},
"GATE":{"name":"Gateway","type":"National Recreation Area","state":"NY,NJ"},
"GARI":{"name":"Gauley River","type":"National Recreation Area","state":"West Virginia"},
"GEGR":{"name":"General Grant","type":"National Memorial","state":"New York"},
"GEMM":{"name":"George Mason","type":"Memorial","state":"District of Columbia"},
"GERO":{"name":"George Rogers Clark","type":"National Historical Park","state":"Indiana"},
"GEWA":{"name":"George Washington Birthplace","type":"National Monument","state":"Virginia"},
"GWCA":{"name":"George Washington Carver","type":"National Monument","state":"Missouri"},
"GWMP":{"name":"George Washington","type":"Memorial Parkway","state":"DC, MD, VA"},
"GETT":{"name":"Gettysburg","type":"National Military Park","state":"Pennsylvania"},
"GICL":{"name":"Gila Cliff Dwellings","type":"National Monument","state":"New Mexico"},
"GLBA":{"name":"Glacier Bay","type":"National Park & Preserve","state":"Alaska"},
"GLAC":{"name":"Glacier","type":"National Park","state":"Montana"},
"GLCA":{"name":"Glen Canyon","type":"National Recreation Area","state":"AZ,UT"},
"GLEC":{"name":"Glen Echo","type":"Park","state":"Maryland"},
"GLDE":{"name":"Gloria Dei Church","type":"National Historic Site","state":"Pennsylvania"},
"GOGA":{"name":"Golden Gate","type":"National Recreation Area","state":"California"},
"GOSP":{"name":"Golden Spike","type":"National Historic Site","state":"Utah"},
"GOIS":{"name":"Governors Island","type":"National Monument","state":"New York"},
"GRCA":{"name":"Grand Canyon","type":"National Park","state":"Arizona"},
"GRPO":{"name":"Grand Portage","type":"National Monument","state":"Minnesota"},
"GRTE":{"name":"Grand Teton","type":"National Park","state":"Wyoming"},
"GRKO":{"name":"Grant-Kohrs Ranch","type":"National Historic Site","state":"Montana"},
"GRBA":{"name":"Great Basin","type":"National Park","state":"Nevada"},
"GREG":{"name":"Great Egg Harbor River","type":"","state":"New Jersey"},
"GRFA":{"name":"Great Falls","type":"Park","state":"Virginia"},
"GRSA":{"name":"Great Sand Dunes","type":"National Park & Preserve","state":"Colorado"},
"GRSM":{"name":"Great Smoky Mountains","type":"National Park","state":"NC,TN"},
"GRSP":{"name":"Green Springs","type":"","state":"Virginia"},
"GREE":{"name":"Greenbelt","type":"Park","state":"Maryland"},
"GUMO":{"name":"Guadalupe Mountains","type":"National Park","state":"Texas"},
"GUCO":{"name":"Guilford Courthouse","type":"National Military Park","state":"North Carolina"},
"GUIS":{"name":"Gulf Islands","type":"National Seashore","state":"FL,MS"},
"GUGE":{"name":"Gullah/Geechee","type":"Cultural Heritage Corridor","state":"FL,GA,NC,SC"},
"HAFO":{"name":"Hagerman Fossil Beds","type":"National Monument","state":"Idaho"},
"HALE":{"name":"Haleakalā","type":"National Park","state":"Hawai'i"},
"HAGR":{"name":"Hamilton Grange","type":"National Memorial","state":"New York"},
"HAMP":{"name":"Hampton","type":"National Historic Site","state":"Maryland"},
"HAHA":{"name":"Harmony Hall","type":"","state":"Maryland"},
"HAFE":{"name":"Harpers Ferry","type":"National Historical Park","state":"WV,VA,MD"},
"HATU":{"name":"Harriet Tubman Underground Railroad","type":"National Monument","state":"Maryland"},
"HSTR":{"name":"Harry S Truman","type":"National Historic Site","state":"Missouri"},
"HAVO":{"name":"Hawai'i Volcanoes","type":"National Park","state":"Hawai'i"},
"HEHO":{"name":"Herbert Hoover","type":"National Historic Site","state":"Iowa"},
"JAME":{"name":"Historic Jamestowne","type":"Part of Colonial National Historical Park","state":"Virginia"},
"PIMA":{"name":"Hohokam Pima","type":"National Monument","state":"Arizona"},
"HOFR":{"name":"Home Of Franklin D Roosevelt","type":"National Historic Site","state":"New York"},
"HOME":{"name":"Homestead","type":"National Monument of America","state":"Nebraska"},
"HONO":{"name":"Honouliuli","type":"National Monument","state":"Hawai'i"},
"HOCU":{"name":"Hopewell Culture","type":"National Historical Park","state":"Ohio"},
"HOFU":{"name":"Hopewell Furnace","type":"National Historic Site","state":"Pennsylvania"},
"HOBE":{"name":"Horseshoe Bend","type":"National Military Park","state":"Alabama"},
"HOSP":{"name":"Hot Springs","type":"National Park","state":"Arkansas"},
"HOVE":{"name":"Hovenweep","type":"National Monument","state":"CO,UT"},
"HUTR":{"name":"Hubbell Trading Post","type":"National Historic Site","state":"Arizona"},
"HURV":{"name":"Hudson River Valley","type":"National Heritage Area","state":"New York"},
"INUP":{"name":"Iñupiat Heritage Center","type":"","state":"Alaska"},
"IATR":{"name":"Ice Age","type":"National Scenic Trail","state":"Wisconsin"},
"INDE":{"name":"Independence","type":"National Historical Park","state":"Pennsylvania"},
"INDU":{"name":"Indiana Dunes","type":"National Lakeshore","state":"Indiana"},
"ISRO":{"name":"Isle Royale","type":"National Park","state":"Michigan"},
"JAGA":{"name":"James A Garfield","type":"National Historic Site","state":"Ohio"},
"JELA":{"name":"Jean Lafitte","type":"National Historical Park and Preserve","state":"Louisiana"},
"JEFF":{"name":"Jefferson","type":"National Expansion Memorial","state":"Missouri"},
"JECA":{"name":"Jewel Cave","type":"National Monument","state":"South Dakota"},
"JICA":{"name":"Jimmy Carter","type":"National Historic Site","state":"Georgia"},
"JODR":{"name":"Grand Teton","type":"National Park","state":"Wyoming"},
"JODA":{"name":"John Day Fossil Beds","type":"National Monument","state":"Oregon"},
"JOER":{"name":"John Ericsson","type":"National Memorial","state":"District of Columbia"},
"JOFI":{"name":"John Fitzgerald Kennedy","type":"National Historic Site","state":"Massachusetts"},
"JOMU":{"name":"John Muir","type":"National Historic Site","state":"California"},
"JOFL":{"name":"Johnstown Flood","type":"National Memorial","state":"Pennsylvania"},
"JOTR":{"name":"Joshua Tree","type":"National Park","state":"California"},
"JTHG":{"name":"Journey Through Hallowed Ground","type":"National Heritage Area","state":"MD,PA,VA,WV"},
"JUBA":{"name":"Juan Bautista de Anza","type":"National Historic Trail","state":"AZ,CA"},
"KALA":{"name":"Kalaupapa","type":"National Historical Park","state":"Hawai'i"},
"KAHO":{"name":"Kaloko-Honokōhau","type":"National Historical Park","state":"Hawai'i"},
"KATM":{"name":"Katmai","type":"National Park & Preserve","state":"Alaska"},
"KEFJ":{"name":"Kenai Fjords","type":"National Park","state":"Alaska"},
"KEAQ":{"name":"Kenilworth Park & Aquatic Gardens","type":"","state":"District of Columbia"},
"KEMO":{"name":"Kennesaw Mountain","type":"National Battlefield Park","state":"Georgia"},
"KEWE":{"name":"Keweenaw","type":"National Historical Park","state":"Michigan"},
"KIMO":{"name":"Kings Mountain","type":"National Military Park","state":"South Carolina"},
"KLSE":{"name":"Klondike Gold Rush - Seattle Unit","type":"National Historical Park","state":"Washington"},
"KLGO":{"name":"Klondike Gold Rush","type":"National Historical Park","state":"Alaska"},
"KNRI":{"name":"Knife River Indian Villages","type":"National Historic Site","state":"North Dakota"},
"KOVA":{"name":"Kobuk Valley","type":"National Park","state":"Alaska"},
"KOWA":{"name":"Korean War Veterans","type":"Memorial","state":"District of Columbia"},
"LACH":{"name":"North Cascades","type":"National Park","state":"Washington"},
"LACL":{"name":"Lake Clark","type":"National Park & Preserve","state":"Alaska"},
"LAME":{"name":"Lake Mead","type":"National Recreation Area","state":"AZ,NV"},
"LAMR":{"name":"Lake Meredith","type":"National Recreation Area","state":"Texas"},
"LARO":{"name":"Lake Roosevelt","type":"National Recreation Area","state":"Washington"},
"LAVO":{"name":"Lassen Volcanic","type":"National Park","state":"California"},
"LABE":{"name":"Lava Beds","type":"National Monument","state":"California"},
"LECL":{"name":"Lewis & Clark","type":"National Historic Trail","state":"ID,IL,IA,KS,MO,MT,NE,ND,OR,SD,WA"},
"LEWI":{"name":"Lewis and Clark","type":"National Historical Park","state":"OR,WA"},
"LIBO":{"name":"Lincoln Boyhood","type":"National Memorial","state":"Indiana"},
"LIHO":{"name":"Lincoln Home","type":"National Historic Site","state":"Illinois"},
"LINC":{"name":"Lincoln","type":"Memorial","state":"District of Columbia"},
"LIBI":{"name":"Little Bighorn Battlefield","type":"National Monument","state":"Montana"},
"LIRI":{"name":"Little River Canyon","type":"National Preserve","state":"Alabama"},
"CHSC":{"name":"Little Rock Central High School","type":"National Historic Site","state":"Arkansas"},
"LONG":{"name":"Longfellow House Washington's Headquarters","type":"National Historic Site","state":"Massachusetts"},
"LOWE":{"name":"Lowell","type":"National Historical Park","state":"Massachusetts"},
"LODE":{"name":"Lower Delaware","type":"National Wild and Scenic River","state":"PA,NJ"},
"LOEA":{"name":"Lower East Side Tenement Museum","type":"National Historic Site","state":"New York"},
"LYJO":{"name":"Lyndon B Johnson","type":"National Historical Park","state":"Texas"},
"LYBA":{"name":"Lyndon Baines Johnson Memorial Grove on the Potomac","type":"","state":"District of Columbia"},
"MAWA":{"name":"Maggie L Walker","type":"National Historic Site","state":"Virginia"},
"MAAC":{"name":"Maine Acadian Culture","type":"","state":"Maine"},
"MACA":{"name":"Mammoth Cave","type":"National Park","state":"Kentucky"},
"MANA":{"name":"Manassas","type":"National Battlefield Park","state":"Virginia"},
"MANZ":{"name":"Manzanar","type":"National Historic Site","state":"California"},
"MABI":{"name":"Marsh - Billings - Rockefeller","type":"National Historical Park","state":"Vermont"},
"MALU":{"name":"Martin Luther King Jr","type":"National Historic Site","state":"Georgia"},
"MLKM":{"name":"Martin Luther King, Jr. Memorial","type":"National Memorial","state":"District of Columbia"},
"MAVA":{"name":"Martin Van Buren","type":"National Historic Site","state":"New York"},
"MAMC":{"name":"Mary McLeod Bethune Council House","type":"National Historic Site","state":"District of Columbia"},
"MEHI":{"name":"Meridian Hill","type":"Park","state":"District of Columbia"},
"MEVE":{"name":"Mesa Verde","type":"National Park","state":"Colorado"},
"MIIN":{"name":"Minidoka","type":"National Historic Site","state":"ID,WA"},
"MIMA":{"name":"Minute Man","type":"National Historical Park","state":"Massachusetts"},
"MIMI":{"name":"Minuteman Missile","type":"National Historic Site","state":"South Dakota"},
"MIDE":{"name":"Mississippi Delta","type":"National Heritage Area","state":"Mississippi"},
"MIGU":{"name":"Mississippi Gulf","type":"National Heritage Area","state":"Mississippi"},
"MIHI":{"name":"Mississippi Hills","type":"National Heritage Area","state":"Mississippi"},
"MISS":{"name":"Mississippi","type":"National River & Recreation Area","state":"Minnesota"},
"MNRR":{"name":"Missouri","type":"National Recreational River","state":"SD,NE"},
"MOJA":{"name":"Mojave","type":"National Preserve","state":"California"},
"MONO":{"name":"Monocacy","type":"National Battlefield","state":"Maryland"},
"MOCA":{"name":"Montezuma Castle","type":"National Monument","state":"Arizona"},
"MOCR":{"name":"Moores Creek","type":"National Battlefield","state":"North Carolina"},
"MOPI":{"name":"Mormon Pioneer","type":"National Historic Trail","state":"IL,IA,NE,UT,WY"},
"MORR":{"name":"Morristown","type":"National Historical Park","state":"New Jersey"},
"AUTO":{"name":"Motor Cities","type":"National Heritage Area","state":"Michigan"},
"MORA":{"name":"Mount Rainier","type":"National Park","state":"Washington"},
"MORU":{"name":"Mount Rushmore","type":"National Memorial","state":"South Dakota"},
"MUWO":{"name":"Muir Woods","type":"National Monument","state":"California"},
"MUSH":{"name":"Muscle Shoals","type":"National Heritage Area","state":"Alabama"},
"NATC":{"name":"Natchez","type":"National Historical Park","state":"Mississippi"},
"NATT":{"name":"Natchez Trace","type":"National Scenic Trail","state":"Mississippi"},
"NATR":{"name":"Natchez Trace","type":"Parkway","state":"AL,MS,TN"},
"AVIA":{"name":"National Aviation","type":"Heritage Area","state":"Ohio"},
"NACE":{"name":"National Capital Parks-East","type":"","state":"District of Columbia"},
"NAMA":{"name":"National Mall & Memorial Parks","type":"","state":"District of Columbia"},
"MALL":{"name":"National Mall","type":"","state":"District of Columbia"},
"NPSA":{"name":"National Park of American Samoa","type":"","state":"American Samoa"},
"NPNH":{"name":"National Parks of New York Harbor","type":"","state":"New York"},
"NWWM":{"name":"World War II Memorial","type":"","state":"District of Columbia"},
"NABR":{"name":"Natural Bridges","type":"National Monument","state":"Utah"},
"NAVA":{"name":"Navajo","type":"National Monument","state":"Arizona"},
"NEBE":{"name":"New Bedford Whaling","type":"National Historical Park","state":"Massachusetts"},
"NEEN":{"name":"New England","type":"National Scenic Trail","state":"MA,CT"},
"NEJE":{"name":"New Jersey Pinelands","type":"National Reserve","state":"New Jersey"},
"PINE":{"name":"New Jersey Pinelands","type":"National Reserve","state":"New Jersey"},
"JAZZ":{"name":"New Orleans Jazz","type":"National Historical Park","state":"Louisiana"},
"NERI":{"name":"New River Gorge","type":"National River","state":"West Virginia"},
"NEPE":{"name":"Nez Perce","type":"National Historical Park","state":"ID,MT,OR,WA"},
"NIFA":{"name":"Niagara Falls","type":"National Heritage Area","state":"New York"},
"NICO":{"name":"Nicodemus","type":"National Historic Site","state":"Kansas"},
"NISI":{"name":"Ninety Six","type":"National Historic Site","state":"South Carolina"},
"NIOB":{"name":"Niobrara","type":"National Scenic River","state":"Nebraska"},
"NOAT":{"name":"Noatak","type":"National Preserve","state":"Alaska"},
"NOCA":{"name":"North Cascades","type":"National Park","state":"Washington"},
"NOCO":{"name":"North Country","type":"National Scenic Trail","state":"MI,MN,ND,NY,OH,PA,WI"},
"NORG":{"name":"Northern Rio Grande","type":"National Heritage Area","state":"New Mexico"},
"OBED":{"name":"Obed","type":"Wild & Scenic River","state":"Tennessee"},
"OCMU":{"name":"Ocmulgee","type":"National Monument","state":"Georgia"},
"OIRE":{"name":"Oil Region","type":"National Heritage Area","state":"Pennsylvania"},
"OKCI":{"name":"Oklahoma City","type":"National Memorial","state":"Oklahoma"},
"OPOT":{"name":"Old Post Office Tower","type":"","state":"District of Columbia"},
"OLSP":{"name":"Old Spanish","type":"National Historic Trail","state":"AZ,CA,CO,NV,NM,UT"},
"OLYM":{"name":"Olympic","type":"National Park","state":"Washington"},
"ORCA":{"name":"Oregon Caves","type":"National Monument & Preserve","state":"Oregon"},
"OREG":{"name":"Oregon","type":"National Historic Trail","state":"ID,KS,MO,NE,OR,WY"},
"ORPI":{"name":"Organ Pipe Cactus","type":"National Monument","state":"Arizona"},
"OVVI":{"name":"Overmountain Victory","type":"National Historic Trail","state":"NC,SC,TN,VA"},
"OXHI":{"name":"Oxon Cove  Park & Oxon Hill Farm","type":"","state":"Maryland"},
"OZAR":{"name":"Ozark","type":"National Scenic Riverways","state":"Missouri"},
"PAIS":{"name":"Padre Island","type":"National Seashore","state":"Texas"},
"PAAL":{"name":"Palo Alto Battlefield","type":"National Historical Park","state":"Texas"},
"PARA":{"name":"Parashant","type":"Grand Canyon-Parashant National Monument","state":"Arizona"},
"PAGR":{"name":"Paterson Great Falls","type":"National Historical Park","state":"New Jersey"},
"PERI":{"name":"Pea Ridge","type":"National Military Park","state":"Arkansas"},
"PECO":{"name":"Pecos","type":"National Historical Park","state":"New Mexico"},
"PIMI":{"name":"Peirce Mill","type":"","state":"District of Columbia"},
"PAAV":{"name":"Pennsylvania Avenue","type":"National Historic Site","state":"District of Columbia"},
"PEVI":{"name":"Perry's Victory & International Peace","type":"Memorial","state":"Ohio"},
"PETE":{"name":"Petersburg","type":"National Battlefield","state":"Virginia"},
"PEFO":{"name":"Petrified Forest","type":"National Park","state":"Arizona"},
"PETR":{"name":"Petroglyph","type":"National Monument","state":"New Mexico"},
"PIRO":{"name":"Pictured Rocks","type":"National Lakeshore","state":"Michigan"},
"PINN":{"name":"Pinnacles","type":"National Park","state":"California"},
"PISP":{"name":"Pipe Spring","type":"National Monument","state":"Arizona"},
"PIPE":{"name":"Pipestone","type":"National Monument","state":"Minnesota"},
"PISC":{"name":"Piscataway","type":"Park","state":"Maryland"},
"PORE":{"name":"Point Reyes","type":"National Seashore","state":"California"},
"POEX":{"name":"Pony Express","type":"National Historic Trail","state":"CA,CO,KS,MO,NE,NV,UT,WY"},
"POCH":{"name":"Port Chicago Naval Magazine","type":"National Memorial","state":"California"},
"POHE":{"name":"Potomac Heritage","type":"National Scenic Trail","state":"DC,MD,PA,VA"},
"POPO":{"name":"Poverty Point","type":"National Monument","state":"Louisiana"},
"WICL":{"name":"President William Jefferson Clinton Birthplace Home","type":"National Historic Site","state":"Arkansas"},
"WHHO":{"name":"President's Park (White House)","type":"","state":"District of Columbia"},
"PRSF":{"name":"Presidio of San Francisco","type":"","state":"California"},
"PRWI":{"name":"Prince William Forest","type":"Park","state":"Virginia"},
"PUHO":{"name":"Pu`uhonua O Hōnaunau","type":"National Historical Park","state":"Hawai'i"},
"PUHE":{"name":"Pu`ukoholā Heiau","type":"National Historic Site","state":"Hawai'i"},
"PULL":{"name":"Pullman","type":"National Monument","state":"Illinois"},
"QUSH":{"name":"Quinebaug & Shetucket Rivers Valley","type":"National Heritage Corridor","state":"Connecticut"},
"RABR":{"name":"Rainbow Bridge","type":"National Monument","state":"Utah"},
"REDW":{"name":"Redwood","type":"National and State Parks","state":"California"},
"RICH":{"name":"Richmond","type":"National Battlefield Park","state":"Virginia"},
"RIGR":{"name":"Rio Grande","type":"Wild & Scenic River","state":"Texas"},
"RIRA":{"name":"River Raisin","type":"National Battlefield Park","state":"Michigan"},
"RIST":{"name":"Rivers Of Steel","type":"National Heritage Area","state":"Pennsylvania"},
"ROCR":{"name":"Rock Creek","type":"Park","state":"District of Columbia"},
"ROMO":{"name":"Rocky Mountain","type":"National Park","state":"Colorado"},
"ROWI":{"name":"Roger Williams","type":"National Memorial","state":"Rhode Island"},
"ROCA":{"name":"Roosevelt Campobello","type":"International Park","state":"ME"},
"RORI":{"name":"Rosie the Riveter WWII Home Front","type":"National Historical Park","state":"California"},
"RUCA":{"name":"Russell Cave","type":"National Monument","state":"Alabama"},
"SAHI":{"name":"Sagamore Hill","type":"National Historic Site","state":"New York"},
"SAGU":{"name":"Saguaro","type":"National Park","state":"Arizona"},
"SACR":{"name":"Saint Croix Island","type":"International Historic Site","state":"Maine"},
"SACN":{"name":"Saint Croix","type":"National Scenic Riverway","state":"WI,MN"},
"SAPA":{"name":"Saint Paul's Church","type":"National Historic Site","state":"New York"},
"SAGA":{"name":"Saint-Gaudens","type":"National Historic Site","state":"New Hampshire"},
"SAMA":{"name":"Salem Maritime","type":"National Historic Site","state":"Massachusetts"},
"SAPU":{"name":"Salinas Pueblo Missions","type":"National Monument","state":"New Mexico"},
"SARI":{"name":"Salt River Bay","type":"National Historical Park and Ecological Preserve","state":"Virgin Islands"},
"SAAN":{"name":"San Antonio Missions","type":"National Historical Park","state":"Texas"},
"SAFR":{"name":"San Francisco Maritime","type":"National Historical Park","state":"California"},
"SAJH":{"name":"San Juan Island","type":"National Historical Park","state":"Washington"},
"SAJU":{"name":"San Juan","type":"National Historic Site","state":"Puerto Rico"},
"SAND":{"name":"Sand Creek Massacre","type":"National Historic Site","state":"Colorado"},
"SAFE":{"name":"Santa Fe","type":"National Historic Trail","state":"CO,KS,MO,NM,OK"},
"SAMO":{"name":"Santa Monica Mountains","type":"National Recreation Area","state":"California"},
"SARA":{"name":"Saratoga","type":"National Historical Park","state":"New York"},
"SAIR":{"name":"Saugus Iron Works","type":"National Historic Site","state":"Massachusetts"},
"SCRV":{"name":"Schuylkill River Valley","type":"National Heritage Area","state":"Pennsylvania"},
"SCBL":{"name":"Scotts Bluff","type":"National Monument","state":"Nebraska"},
"SEMO":{"name":"Selma To Montgomery","type":"National Historic Trail","state":"Alabama"},
"SEKI":{"name":"Sequoia & Kings Canyon","type":"National Parks","state":"California"},
"SHEN":{"name":"Shenandoah","type":"National Park","state":"Virginia"},
"SHVB":{"name":"Shenandoah Valley Battlefields","type":"National Historic District","state":"West Virginia"},
"SHIL":{"name":"Shiloh","type":"National Military Park","state":"TN,MS"},
"SITK":{"name":"Sitka","type":"National Historical Park","state":"Alaska"},
"SLBE":{"name":"Sleeping Bear Dunes","type":"National Lakeshore","state":"Michigan"},
"SOCA":{"name":"South Carolina","type":"National Heritage Corridor","state":"South Carolina"},
"SPAR":{"name":"Springfield Armory","type":"National Historic Site","state":"Massachusetts"},
"STSP":{"name":"Star-Spangled Banner","type":"National Historic Trail","state":"DC, MD, VA"},
"STLI":{"name":"Statue Of Liberty","type":"National Monument","state":"New York"},
"STEA":{"name":"Steamtown","type":"National Historic Site","state":"Pennsylvania"},
"STRI":{"name":"Stones River","type":"National Battlefield","state":"Tennessee"},
"SUCR":{"name":"Sunset Crater Volcano","type":"National Monument","state":"Arizona"},
"TAPR":{"name":"Tallgrass Prairie","type":"National Preserve","state":"Kansas"},
"TECW":{"name":"Tennessee Civil War","type":"National Heritage Area","state":"Tennessee"},
"THKO":{"name":"Thaddeus Kosciuszko","type":"National Memorial","state":"Pennsylvania"},
"OLST":{"name":"The Old Stone House","type":"","state":"District of Columbia"},
"THRB":{"name":"Theodore Roosevelt Birthplace","type":"National Historic Site","state":"New York"},
"THRI":{"name":"Theodore Roosevelt Inaugural","type":"National Historic Site","state":"New York"},
"THIS":{"name":"Theodore Roosevelt Island","type":"","state":"District of Columbia"},
"THRO":{"name":"Theodore Roosevelt","type":"National Park","state":"North Dakota"},
"THCO":{"name":"Thomas Cole","type":"National Historic Site","state":"New York"},
"EDIS":{"name":"Thomas Edison","type":"National Historical Park","state":"New Jersey"},
"THJE":{"name":"Thomas Jefferson","type":"Memorial","state":"District of Columbia"},
"THST":{"name":"Thomas Stone","type":"National Historic Site","state":"Maryland"},
"TICA":{"name":"Timpanogos Cave","type":"National Monument","state":"Utah"},
"TIMU":{"name":"Timucuan","type":"Ecological & Historic Preserve","state":"Florida"},
"TONT":{"name":"Tonto","type":"National Monument","state":"Arizona"},
"TOSY":{"name":"Touro Synagogue","type":"National Historic Site","state":"Rhode Island"},
"TRTE":{"name":"Trail Of Tears","type":"National Historic Trail","state":"AL,AR,GA,IL,KY,MO,NC,OK,TN"},
"TULE":{"name":"Tule Lake Unit","type":"","state":"CA"},
"TUSK":{"name":"Tule Springs Fossil Beds","type":"National Monument","state":"Nevada"},
"TUMA":{"name":"Tumacácori","type":"National Historical Park","state":"Arizona"},
"TUPE":{"name":"Tupelo","type":"National Battlefield","state":"Mississippi"},
"TUAI":{"name":"Tuskegee Airmen","type":"National Historic Site","state":"Alabama"},
"TUIN":{"name":"Tuskegee Institute","type":"National Historic Site","state":"Alabama"},
"TUZI":{"name":"Tuzigoot","type":"National Monument","state":"Arizona"},
"ULSG":{"name":"Ulysses S Grant","type":"National Historic Site","state":"Missouri"},
"UPDE":{"name":"Upper Delaware","type":"Scenic & Recreational River","state":"NY,PA"},
"UPHV":{"name":"Upper Housatonic Valley","type":"National Heritage Area","state":"CT,MA"},
"VAFO":{"name":"Valley Forge","type":"National Historical Park","state":"Pennsylvania"},
"VAMA":{"name":"Vanderbilt Mansion","type":"National Historic Site","state":"New York"},
"VICK":{"name":"Vicksburg","type":"National Military Park","state":"Mississippi"},
"VIVE":{"name":"Vietnam Veterans","type":"Memorial","state":"District of Columbia"},
"VICR":{"name":"Virgin Islands Coral Reef","type":"National Monument","state":"Virgin Islands"},
"VIIS":{"name":"Virgin Islands","type":"National Park","state":"Virgin Islands"},
"VOYA":{"name":"Voyageurs","type":"National Park","state":"Minnesota"},
"WACA":{"name":"Walnut Canyon","type":"National Monument","state":"Arizona"},
"WAPA":{"name":"War In The Pacific","type":"National Historical Park","state":"Guam"},
"WAMO":{"name":"Washington Monument","type":"","state":"District of Columbia"},
"WARO":{"name":"Washington-Rochambeau","type":"National Historic Trail","state":"MA,RI,CT,NY,NJ,PA,DE,MD,VA,DC"},
"WABA":{"name":"Washita Battlefield","type":"National Historic Site","state":"Oklahoma"},
"WEFA":{"name":"Weir Farm","type":"National Historic Site","state":"Connecticut"},
"WHEE":{"name":"Wheeling","type":"National Heritage Area","state":"West Virginia"},
"WHIS":{"name":"Whiskeytown","type":"National Recreation Area","state":"California"},
"WHSA":{"name":"White Sands","type":"National Monument","state":"New Mexico"},
"WHMI":{"name":"Whitman Mission","type":"National Historic Site","state":"Washington"},
"WIHO":{"name":"William Howard Taft","type":"National Historic Site","state":"Ohio"},
"WICR":{"name":"Wilson's Creek","type":"National Battlefield","state":"Missouri"},
"WICA":{"name":"Wind Cave","type":"National Park","state":"South Dakota"},
"WOTR":{"name":"Wolf Trap National Park for the Performing Arts","type":"","state":"Virginia"},
"WORI":{"name":"Women's Rights","type":"National Historical Park","state":"New York"},
"WWII":{"name":"World War II Memorial","type":"","state":"District of Columbia"},
"USAR":{"name":"World War II Valor in the Pacific","type":"National Monument","state":"HI,AK,CA"},
"WRST":{"name":"Wrangell - St Elias","type":"National Park & Preserve","state":"Alaska"},
"WRBR":{"name":"Wright Brothers","type":"National Memorial","state":"North Carolina"},
"WUPA":{"name":"Wupatki","type":"National Monument","state":"Arizona"},
"YELL":{"name":"Yellowstone","type":"National Park","state":"ID,MT,WY"},
"YORK":{"name":"Yorktown Battlefield","type":"Part of Colonial National Historical Park","state":"Virginia"},
"YOSE":{"name":"Yosemite","type":"National Park","state":"California"},
"YUHO":{"name":"Yucca House","type":"National Monument","state":"Colorado"},
"YUCH":{"name":"Yukon - Charley Rivers","type":"National Preserve","state":"Alaska"},
"YUCR":{"name":"Yuma Crossing","type":"National Heritage Area","state":"Arizona"},
"ZION":{"name":"Zion","type":"National Park","state":"Utah"}
};
